# $Id: calc.bnf 5 2009-08-21 21:47:38Z Mikael Patel $
# ----------------------------------------------------------------------
# Name
#   calc - simple expression grammar
#  
# Description:	
#   Simple expression grammar for arithmetic expressions with priority
#   and left-to-right ordering. Demonstrates debugging of the grammar.
#
# Usage:
#   parse calc.bnf
#
# Copyright (C) 1984-1994, 2013, Mikael Patel.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General
# Public License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330,
# Boston, MA  02111-1307  USA
# ----------------------------------------------------------------------

# Grammar definition

!xbnf
<calc> ::= <expr> <eoln> @ display
<expr> ::= <term3>
<term3> ::= <term2> <prio3*>
<prio3> ::= | <term2> @ or
<term2> ::= <term1> <prio2*>
<prio2> ::= & <term1> @ and
<term1> ::= <term0> <prio1*>
<prio1> ::= - <term0> @ sub
         |  + <term0> @ add
<term0> ::= <fact> <prio0?> 
<prio0> ::= * <term0> @ mul
	 |  / <term0> @ div
         |  % <term0> @ mod
<fact> ::= ( <expr> ) 
	|  <integer> @ value_print
	|  <error>

# Test the grammar
?calc
?fact
!calc

